// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0VX76g8rDIr4RYLRu0QfrhKS-4i1mOTI',
    appId: '1:1039517302:web:7592d79e9af1f01bee4157',
    messagingSenderId: '1039517302',
    projectId: 'gohit-a7f21',
    authDomain: 'gohit-a7f21.firebaseapp.com',
    storageBucket: 'gohit-a7f21.appspot.com',
    measurementId: 'G-JC3GYVFW58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj8UubcIZvzOgAc9MKBWwYta0i8i9b8yc',
    appId: '1:1039517302:android:eaa8a43c242551fdee4157',
    messagingSenderId: '1039517302',
    projectId: 'gohit-a7f21',
    storageBucket: 'gohit-a7f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbgpj2aJ2aJQ4P6MyRSooQvELIp9Edmk',
    appId: '1:1039517302:ios:95ffe84d5c47b47bee4157',
    messagingSenderId: '1039517302',
    projectId: 'gohit-a7f21',
    storageBucket: 'gohit-a7f21.appspot.com',
    iosClientId: '1039517302-ktu74t5n3q6uosgipq0fe0fq4f8r5atq.apps.googleusercontent.com',
    iosBundleId: 'com.dev.gohit',
  );
}
